CONFIG_ZMK_KEYBOARD_NAME="roBa"

CONFIG_ZMK_POINTING=y
CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_Y=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=200

CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y

CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ZMK / DYA Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y

CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y

# Runtime editable combo / macro
CONFIG_ZMK_CUSTOM_SETTINGS=y
CONFIG_ZMK_CUSTOM_SETTINGS_STUDIO_RPC=y
CONFIG_ZMK_CUSTOM_SETTINGS_LARGE_VALUE_MAX_SIZE=256

CONFIG_ZMK_RUNTIME_COMBO=y
CONFIG_ZMK_RUNTIME_COMBO_STUDIO_RPC=y

CONFIG_ZMK_RUNTIME_MACRO=y
CONFIG_ZMK_RUNTIME_MACRO_STUDIO_RPC=y

CONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y
CONFIG_ZMK_BEHAVIOR_LOCAL_IDS_IN_BINDINGS=y

# Physical layout metadata for DYA Studio
CONFIG_ZMK_PHYSICAL_LAYOUTS_FEATURE=y
CONFIG_ZMK_PHYSICAL_LAYOUTS_FEATURE_STUDIO_RPC=y

# PMW3610 settings / diagnostics in DYA Studio
CONFIG_ZMK_PMW3610_CUSTOM_SETTINGS=y
CONFIG_ZMK_PMW3610_STUDIO_RPC=y

CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240

# Custom RPC payloads used by macro/combo/PMW3610
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=4096
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=256
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=256
CONFIG_ZMK_STUDIO_RPC_CUSTOM_SUBSYSTEM_REQUEST_PAYLOAD_MAX_BYTES=256
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=6000
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000


# XIAO BLE RGB LED battery / connection indicator
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
